### PR TITLE
PolymorphicQuerySet: Prevent NoneType error in test___lookup

### PR DESCRIPTION
**Pull request by hll1682003**
## Description:
This PR ensures that test___lookup only processes non-None source_expression values to prevent potential NoneType errors. The change adds a simple condition to check if source_expression is None before passing it to test___lookup.

## Changes:

Added a None check for source_expression before calling test___lookup.
Why this is needed:

- Prevents potential NoneType errors when evaluating query expressions.
- Ensures test___lookup is only invoked with valid values.
- Our unit tests start failing after migrating from Django 5.0.10 to 5.1.5 and start showing "AttributeError: 'NoneType' object has no attribute 'name'"
- Inspired by [this fix](https://github.com/jazzband/django-polymorphic/commit/88922d7d5e918f1338eeb9baeecb17ed98ed1261), which addressed a similar issue in django-polymorphic.

### CODE REVIEW

**Comment by bckohan** [comment]
Fixes #616

**Review by bckohan — APPROVED** [review]
This fix is correct. The alternative would be to do the none check in the else statement below, but I can find no other places where test__lookup is called on a potentially None value in the code.

**Comment by hll1682003** [comment]
Thanks @bckohan for your review!
